### ISSUE TITLE
Duplicate Emails

### ISSUE THREAD

**Issue by btotharye** [vespene-io/vespene#44] opened 2018-10-30 15:23 UTC
By default the Django auth model only allows uniqueness for usernames not emails.  I have a custom user model already if you want me to submit it that will allow for unique email and username and can allow to login with whichever one you want to setup as default.

let me know, thanks

**Comment by mpdehaan** [comment] 2018-10-30 15:37
Just to clarify, the issue is you want two accounts with the same email or something else?

I've been adding new users in the main Vespene UI without going to /admin, and the email address there isn't required.

**Comment by mpdehaan** [comment] 2018-10-30 15:48
Re-reading this I think I understand now.  This would make them have to be unique.

I think I'm not really wanting to migrate the current user model at this time.  Can you just change this in settings without modifying the rest of the code and adding a migration?  I can see where keeping up with a migration on the side would be weird.

**Comment by btotharye** [comment] 2018-10-30 15:59
I’ll check but don’t think so I think it has to be a custom user model I ran into this on my app.  It doesn’t matter to me if it’s by username just thought I’d mention it

**Comment by mpdehaan** [comment] 2018-10-30 17:44
Sure --- Yeah, I'm curious and would like to see the link to it for sure so I can learn more about auth model bits, but yeah probably don't want to change it right at this time.   Hope that makes sense.

**Comment by mpdehaan** [comment] 2018-10-30 18:09
I'm going to close this one as feature discussion should really happen on talk.vespene.io - and I need to keep this for open PRs and bug reports.  Not trying to end discussion just cleaning up.

**Closed by mpdehaan** 2018-10-30 18:09 UTC
